# Sampling and log probs

> In this post, we will learn the sampling and log probability of distribution. This is the summary of lecture "Probabilistic Deep Learning with Tensorflow 2" from Coursera.

- toc: true 
- badges: true
- comments: true
- author: Chanseok Kang
- categories: [Python, Coursera, Deep_Learning, Tensorflow, Probability]
- image: 

In [2]:
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
tfd = tfp.distributions

plt.rcParams['figure.figsize'] = (16, 10)

print("Tensorflow : v" + tf.__version__)
print("Tensorflow probability : v" + tfp.__version__)

Tensorflow : v2.3.1
Tensorflow probability : v0.11.1


## Examples

In [4]:
exp = tfd.Exponential(rate=[[1., 1.5, 0.8], [0.3, 0.4, 1.8]])
print(exp)

tfp.distributions.Exponential("Exponential", batch_shape=[2, 3], event_shape=[], dtype=float32)


In [5]:
ind_exp = tfd.Independent(exp)
print(ind_exp)

tfp.distributions.Independent("IndependentExponential", batch_shape=[2], event_shape=[3], dtype=float32)


In [6]:
# Sample, batch, event_shape
ind_exp.sample(4)

<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[0.9336921 , 1.1014012 , 0.95849776],
        [1.859738  , 1.5860045 , 0.6979616 ]],

       [[0.45026   , 0.08602523, 1.4929458 ],
        [2.1974816 , 1.9354982 , 2.1604896 ]],

       [[0.14067604, 0.13271774, 0.5351997 ],
        [2.0170953 , 0.44593987, 0.6286139 ]],

       [[0.6865209 , 1.2604585 , 0.3267352 ],
        [7.852364  , 1.1664017 , 1.066288  ]]], dtype=float32)>

In [7]:
rates = [
    [[[1., 1.5, 0.8], [0.3, 0.4, 1.8]]],
    [[[0.2, 0.4, 1.4], [0.4, 1.1, 0.9]]]
]

exp = tfd.Exponential(rate=rates)
ind_exp = tfd.Independent(exp, reinterpreted_batch_ndims=2)

print(exp)
print(ind_exp)

tfp.distributions.Exponential("Exponential", batch_shape=[2, 1, 2, 3], event_shape=[], dtype=float32)
tfp.distributions.Independent("IndependentExponential", batch_shape=[2, 1], event_shape=[2, 3], dtype=float32)


In [8]:
ind_exp.sample([4, 2])

<tf.Tensor: shape=(4, 2, 2, 1, 2, 3), dtype=float32, numpy=
array([[[[[[4.2317632e-01, 3.0489284e-01, 9.0440281e-02],
           [2.3724518e+00, 2.0689788e+00, 1.1605508e+00]]],


         [[[4.0992074e+00, 2.3008916e+00, 1.2091119e+00],
           [2.8646481e+00, 1.0102176e-01, 2.6999652e-01]]]],



        [[[[1.0713497e+00, 5.1539797e-02, 1.4517514e-01],
           [2.7249320e+00, 8.7734246e-01, 2.6865232e-01]]],


         [[[1.9503578e+01, 1.1081877e+00, 1.9015626e+00],
           [1.7259812e+00, 4.4414407e-01, 4.0184917e+00]]]]],




       [[[[[6.7009032e-01, 1.1803232e-02, 1.8138820e+00],
           [8.3526602e+00, 1.4914610e+00, 6.1227548e-01]]],


         [[[7.1173310e+00, 3.6172342e+00, 2.3583232e-01],
           [7.0146952e+00, 6.4747000e-01, 1.5199455e+00]]]],



        [[[[2.0505677e-01, 2.2933252e-01, 1.4931535e+00],
           [3.0053165e+00, 5.2224517e+00, 4.1780460e-01]]],


         [[[2.4266434e+00, 6.4278895e-01, 1.8892743e-01],
           [3.5566807e-01, 1.15483

In [9]:
ind_exp.log_prob(0.5)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-4.2501554],
       [-5.3155975]], dtype=float32)>

In [10]:
# Broadcasting
ind_exp.log_prob([[0.3, 0.5, 0.8]])

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-4.770155],
       [-5.885597]], dtype=float32)>

In [11]:
ind_exp.log_prob(tf.random.uniform((5, 1, 1, 2, 1)))

<tf.Tensor: shape=(5, 2, 1), dtype=float32, numpy=
array([[[-4.6889906],
        [-5.353305 ]],

       [[-4.0902996],
        [-5.5923157]],

       [[-2.566263 ],
        [-4.05225  ]],

       [[-2.7958922],
        [-4.4053006]],

       [[-2.4176977],
        [-4.136319 ]]], dtype=float32)>

## Coding Tutorial

In [12]:
# Make Multivariate Distribution
normal_distributions = tfd.MultivariateNormalDiag(loc=[[0.5, 1], [0.1, 0], [0, 0.2]],
                                                  scale_diag=[[2, 3], [1, 3], [4, 4]])
normal_distributions

<tfp.distributions.MultivariateNormalDiag 'MultivariateNormalDiag' batch_shape=[3] event_shape=[2] dtype=float32>

In [13]:
normal_distributions.sample(5)

<tf.Tensor: shape=(5, 3, 2), dtype=float32, numpy=
array([[[ 0.47599712,  2.3994164 ],
        [ 1.1864761 ,  1.6828698 ],
        [-4.9358287 ,  1.0669106 ]],

       [[ 2.0767107 , -2.5989242 ],
        [-0.13957322,  0.47952217],
        [ 2.6879144 , -0.72602165]],

       [[-0.21863753, -0.04923904],
        [-0.567453  , -2.7127376 ],
        [-0.53446406, -1.1026759 ]],

       [[ 0.7530515 ,  2.6175892 ],
        [-0.75680864, -3.3777373 ],
        [ 2.1403995 ,  2.210537  ]],

       [[-3.1377547 ,  0.89707947],
        [-1.7728709 ,  6.2212987 ],
        [-1.9061239 ,  0.20411325]]], dtype=float32)>

In [14]:
# Multivariate Normal batched Distribution

loc = [[[0.3, 1.5, 1.], [0.2, 0.4, 2.8]],
       [[2., 2.3, 8], [1.4, 1, 1.3]]]
scale_diag = [0.4, 1., 0.7]
normal_distributions = tfd.MultivariateNormalDiag(loc=loc, scale_diag=scale_diag)
normal_distributions

<tfp.distributions.MultivariateNormalDiag 'MultivariateNormalDiag' batch_shape=[2, 2] event_shape=[3] dtype=float32>

In [15]:
# Use independent to move part of the batch shape
ind_normal_distributions = tfd.Independent(normal_distributions,
                                           reinterpreted_batch_ndims=1)
ind_normal_distributions

<tfp.distributions.Independent 'IndependentMultivariateNormalDiag' batch_shape=[2] event_shape=[2, 3] dtype=float32>

In [16]:
samples = ind_normal_distributions.sample(5)
samples.shape

TensorShape([5, 2, 2, 3])

In [17]:
# [B, E] shaped input
inp = tf.random.uniform((2, 2, 3))
ind_normal_distributions.log_prob(inp)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-10.663086, -73.64146 ], dtype=float32)>

In [18]:
# [E] shaped input (broadcasting over batch size)
inp = tf.random.uniform((2, 3))
ind_normal_distributions.log_prob(inp)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-10.561053, -61.601433], dtype=float32)>

In [19]:
# [S, B, E] shaped input (broadcasting over samples)
inp = tf.random.uniform((9, 2, 2, 3))
ind_normal_distributions.log_prob(inp)

<tf.Tensor: shape=(9, 2), dtype=float32, numpy=
array([[ -9.327406, -80.234634],
       [ -9.255189, -71.55394 ],
       [-10.053996, -70.705414],
       [-12.143329, -66.72578 ],
       [-10.251413, -66.373   ],
       [-10.405237, -72.52043 ],
       [-10.011557, -66.78318 ],
       [-10.101498, -74.51347 ],
       [ -8.64311 , -72.493744]], dtype=float32)>

In [20]:
# [S, b, e] shaped input, where [b, e] is broadcastable over [B, E]
inp = tf.random.uniform((5, 1, 2, 1))
ind_normal_distributions.log_prob(inp)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ -9.530364, -67.75916 ],
       [-10.439697, -83.35648 ],
       [ -9.748083, -73.85253 ],
       [ -9.404794, -62.255707],
       [-10.059189, -81.1289  ]], dtype=float32)>

### Naive Bayes examples

In [21]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import f1_score

In [22]:
# Making a function get_data which:
#   1) Fetches the 20 newsgroup dataset
#   2) Performs a word count on the articles and binarizes the result
#   3) Returns the data as a numpy matrix with the labels

def get_data(categories):
    
    newsgroups_train_data = fetch_20newsgroups(data_home='20_Newsgroup_Data/',
                                               subset='train', categories=categories)
    newsgroups_test_data = fetch_20newsgroups(data_home='20_Newsgroup_Data/',
                                              subset='test', categories=categories)

    n_documents = len(newsgroups_train_data['data'])
    count_vectorizer = CountVectorizer(input='content', binary=True,max_df=0.25, min_df=1.01/n_documents)
    
    train_binary_bag_of_words = count_vectorizer.fit_transform(newsgroups_train_data['data'])
    test_binary_bag_of_words = count_vectorizer.transform(newsgroups_test_data['data']) 

    return (train_binary_bag_of_words.todense(), newsgroups_train_data['target']),  (test_binary_bag_of_words.todense(), newsgroups_test_data['target'])

In [23]:
# Defining a function to conduct Laplace smoothing. This adds a base level of probability for a given feature
# to occur in every class.

def laplace_smoothing(labels, binary_data, n_classes):
    # Compute the parameter estimates (adjusted fraction of documents in class that contain word)
    n_words = binary_data.shape[1]
    alpha = 1 # parameters for Laplace smoothing
    theta = np.zeros([n_classes, n_words]) # stores parameter values - prob. word given class
    for c_k in range(n_classes): # 0, 1, ..., 19
        class_mask = (labels == c_k)
        N = class_mask.sum() # number of articles in class
        theta[c_k, :] = (binary_data[class_mask, :].sum(axis=0) + alpha)/(N + alpha*2)

    return theta

In [24]:
# Getting a subset of the 20 newsgroup dataset

categories = ['alt.atheism', 'talk.religion.misc', 'comp.graphics', 'sci.space']

(train_data, train_labels), (test_data, test_labels) = get_data(categories=categories)
smoothed_counts = laplace_smoothing(labels=train_labels, binary_data=train_data, n_classes=len(categories))

To now make our NB classifier we need to build three functions:
* Compute the class priors
* Build our class conditional distributions
* Put it all together and classify our data

In [25]:
# Function which computes the prior probability of every class based on frequency of occurence in 
# the dataset

def class_priors(n_classes, labels):
    counts = np.zeros(n_classes)
    for c_k in range(n_classes):
        counts[c_k] = np.sum(np.where(labels==c_k, 1, 0))
    priors = counts / np.sum(counts)
    print('The class priors are {}'.format(priors))
    return priors

In [26]:
priors = class_priors(n_classes=len(categories), labels=train_labels)

The class priors are [0.2359882  0.28711898 0.29154376 0.18534907]


In [27]:
# Now we will do a function that given the feature occurence counts returns a Bernoulli distribution of 
# batch_shape=number of classes and event_shape=number of features.
def make_distribution(probs):
    batch_of_bernoullis = tfd.Bernoulli(probs=probs)
    dist = tfd.Independent(batch_of_bernoullis,
                           reinterpreted_batch_ndims=1)
    
    return dist

tf_dist = make_distribution(smoothed_counts)
tf_dist

<tfp.distributions.Independent 'IndependentBernoulli' batch_shape=[4] event_shape=[17495] dtype=int32>

In [28]:
# The final function predict_sample which given the distribution, a test sample, and the class priors:
#   1) Computes the class conditional probabilities given the sample
#   2) Forms the joint likelihood
#   3) Normalises the joint likelihood and returns the log prob
def predict_sample(dist, sample, priors):
    cond_probs = dist.log_prob(sample)
    joint_likelihood = tf.add(np.log(priors), cond_probs)
    norm_factor = tf.math.reduce_logsumexp(joint_likelihood, axis=-1, keepdims=True)
    log_prob = joint_likelihood - norm_factor
    return log_prob

### Computing log_probs

In [29]:
# Predicting one example from our test data
log_probs = predict_sample(tf_dist, test_data[0], priors)
log_probs

<tf.Tensor: shape=(4,), dtype=float32, numpy=
array([-6.1736343e+01, -1.5258789e-05, -1.1620026e+01, -6.3327866e+01],
      dtype=float32)>

In [30]:
# Loop over our test data and classify.
probabilities = []
for sample, label in zip(test_data, test_labels):
    probabilities.append(tf.exp(predict_sample(tf_dist, sample, priors)))

probabilities = np.asarray(probabilities)
predicted_classes = np.argmax(probabilities, axis =-1)
print('f1 ', f1_score(test_labels, predicted_classes, average='macro'))

f1  0.7848499112849504


In [31]:
# Make a Bernoulli Naive Bayes classifier using sklearn with the same level of alpha smoothing. 
clf = BernoulliNB(alpha=1)
clf.fit(train_data, train_labels)
pred = clf.predict(test_data)
print('f1 from sklean ', f1_score(test_labels, pred, average='macro'))

f1 from sklean  0.7848499112849504
