# List vs. Numpy Array

> In this post, we will compare list and numpy array. This is the summary of lecture "Inferential Statistical Analysis with Python" from University of Michigan.

- toc: true 
- badges: true
- comments: true
- author: Chanseok Kang
- categories: [Python, Coursera, Statistics, Umich]
- image: 

## Packages

In [1]:
import numpy as np
import pandas as pd

In [2]:
my_list = [1, 'Colorado', 4.7]
my_list

[1, 'Colorado', 4.7]

In [3]:
my_list[0]

1

In [4]:
my_list[-1]

4.7

In [5]:
my_array = np.array([1, 2, 3])
my_array

array([1, 2, 3])

In [6]:
my_array = np.array((2, 3, 4))
my_array

array([2, 3, 4])

In [7]:
my_array[0]

2

In [8]:
my_array[-1]

4

In [9]:
my_list = [1, 2, 3]
my_array = np.array([1, 2, 3])

In [10]:
my_array / 3

array([0.33333333, 0.66666667, 1.        ])

In [11]:
my_list / 3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [12]:
my_list.append('new thing') # in-place operation
my_list

[1, 2, 3, 'new thing']

In [13]:
my_array = np.append(my_array, 5)
my_array

array([1, 2, 3, 5])

In [14]:
my_dict = {'key1': 'first value', 'key2': 'second value'}
my_dict

{'key1': 'first value', 'key2': 'second value'}

In [15]:
my_dict['key1']

'first value'

In [16]:
my_dict['key3'] = 'third value'

In [17]:
my_dict

{'key1': 'first value', 'key2': 'second value', 'key3': 'third value'}

In [18]:
df = pd.DataFrame({'col1': range(0, 3), 'col2': range(3, 6)})
df

col1  col2
0     0     3
1     1     4
2     2     5

In [20]:
df.rename(columns={'col1': 'apples', 'col2': 'oranges'}, inplace=True)
df

apples  oranges
0       0        3
1       1        4
2       2        5