# The Sequential Model API

> In this post, we will dig into the basic usage of building neural network with Tensorflow Sequential APIs.

- toc: true 
- badges: true
- comments: true
- author: Chanseok Kang
- categories: [Python, Deep_Learning, Tensorflow-Keras]
- image: 

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
print("NumPy: {}".format(np.__version__))
print("Pandas: {}".format(pd.__version__))
print("Tensorflow: {}".format(tf.__version__))

NumPy: 1.18.1
Pandas: 1.0.1
Tensorflow: 2.3.1


## Building a sequential model


### Coding Tutorial - Build a feedforward neural network model

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Softmax

In [7]:
# Build the Sequential feedforward neural network model
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(16, activation='relu'),
    Dense(16, activation='relu'),
    Dense(16, activation='relu'),
    Softmax()
])

In [8]:
# Print the model init weights
model.weights

[<tf.Variable 'dense_6/kernel:0' shape=(784, 16) dtype=float32, numpy=
 array([[ 0.00632718,  0.03422058,  0.05356945, ..., -0.08094531,
         -0.06883492,  0.03079135],
        [ 0.05470668, -0.00311697,  0.0467473 , ...,  0.07579429,
         -0.07043974, -0.0396277 ],
        [-0.06392416, -0.0011922 ,  0.02996352, ...,  0.0302299 ,
          0.08600625, -0.02730832],
        ...,
        [-0.07547824, -0.04853161,  0.04285604, ..., -0.00952245,
         -0.03184244, -0.04670041],
        [-0.04122717, -0.06785581,  0.07500492, ...,  0.01489741,
          0.01860486,  0.01162079],
        [-0.05346318, -0.03413032, -0.01837383, ...,  0.00391962,
         -0.0150687 ,  0.05119966]], dtype=float32)>,
 <tf.Variable 'dense_6/bias:0' shape=(16,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)>,
 <tf.Variable 'dense_7/kernel:0' shape=(16, 16) dtype=float32, numpy=
 array([[ 0.33172336, -0.04824582, -0.06198013, -0.283

In [9]:
# Print the model summary
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 16)                12560     
_________________________________________________________________
dense_7 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_8 (Dense)              (None, 16)                272       
_________________________________________________________________
softmax (Softmax)            (None, 16)                0         
Total params: 13,104
Trainable params: 13,104
Non-trainable params: 0
_________________________________________________________________


## Convolutional and pooling layers
### Coding Tutorial - Build Convolutional Neural network model


In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D

In [17]:
# Build the Sequential convolutional neural network model
model = Sequential([
    Conv2D(16, (3, 3), padding='SAME', strides=2, activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D((3, 3)),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

In [18]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 14, 14, 16)        160       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 4, 4, 16)          0         
_________________________________________________________________
flatten_4 (Flatten)          (None, 256)               0         
_________________________________________________________________
dense_13 (Dense)             (None, 64)                16448     
_________________________________________________________________
dense_14 (Dense)             (None, 10)                650       
Total params: 17,258
Trainable params: 17,258
Non-trainable params: 0
_________________________________________________________________


Currently, the default tensorflow data type is 'channels_last', but we can change it with `data_format` argument.

In [23]:
model = Sequential([
    Conv2D(16, (3, 3), padding='SAME', strides=2, activation='relu', input_shape=(1, 28, 28), data_format='channels_first'),
    MaxPooling2D((3, 3), data_format='channels_first'),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 16, 14, 14)        160       
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 16, 4, 4)          0         
_________________________________________________________________
flatten_7 (Flatten)          (None, 256)               0         
_________________________________________________________________
dense_17 (Dense)             (None, 64)                16448     
_________________________________________________________________
dense_18 (Dense)             (None, 10)                650       
Total params: 17,258
Trainable params: 17,258
Non-trainable params: 0
_________________________________________________________________
