# Eager Execution

> In this post, you will try some features offered from Eager Execution. This is the summary of lecture "Custom and Distributed Training with Tensorflow" from DeepLearning.AI.

- toc: true 
- badges: true
- comments: true
- author: Chanseok Kang
- categories: [Python, Coursera, Tensorflow, DeepLearining.AI]
- image: 

## TL;DR - Eager Execution in Tensorflow

- Evaluate values immediately
- Broadcasting support
- Operator overloading
- NumPy compatibility

## Packages

In [1]:
import tensorflow as tf
import numpy as np

## Evaluate Tensors

In [2]:
x = 2
x_squared = tf.square(x)
x

2

In [3]:
print('hello, {}'.format(x_squared))

hello, 4


## Broadcast values

In [4]:
a = tf.constant([[1, 2],
                 [3, 4]])

In [5]:
tf.add(a, 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [6]:
a ** 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

## NumPy Compatibility

In [7]:
a = tf.constant(5)
b = tf.constant(3)

In [8]:
np.multiply(a, b)

15

## NumPy interoperability

In [9]:
ndarray = np.ones([3, 3])
ndarray

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
tensor = tf.multiply(ndarray, 3)
tensor

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])>

In [11]:
tensor.numpy()

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

## Evaluating variables

In [32]:
v = tf.Variable(0.)
v + 1

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [33]:
v.assign_add(1)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=1.0>

Note that, you can `UnreadVariable` property defined in tensor. It means that it keep track whether the variable was evaluated in a session.

In [36]:
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>

In [37]:
v.read_value()

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

## Examine custom layers

In [38]:
class MyLayer(tf.keras.layers.Layer):
    def __init__(self):
        super(MyLayer, self).__init__()
        self.my_var = tf.Variable(100)
        self.my_other_var_list = [tf.Variable(x) for x in range(2)]

In [39]:
m = MyLayer()

In [40]:
[variable.numpy() for variable in m.variables]

[100, 0, 1]

## Change data types

In [41]:
tensor = tf.constant([1, 2, 3])
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [42]:
# cast a constant integer tensor into floating point
tensor = tf.cast(tensor, dtype=tf.float32)

In [43]:
tensor.dtype

tf.float32